local L = LibStub("AceLocale-3.0"):NewLocale("GladiusEx", "enUS", true)

-- Cooldowns module
L["cat:pvp_trinket"] = "PvP Trinket"
L["cat:mass_dispel"] = "Mass Dispel"
L["cat:cc"] = "CC"
L["cat:offensive"] = "Offensive"
L["cat:defensive"] = "Defensive"
L["cat:silence"] = "Silence"
L["cat:interrupt"] = "Interrupt"
L["cat:dispel"] = "Dispel"
L["cat:heal"] = "Heal"
L["cat:knockback"] = "Knockback"
L["cat:stun"] = "Stun"
L["cat:immune"] = "Immune"
L["cat:uncat"] = "Uncategorized"

-- Tags module
L["WARRIOR:short"] = "Warr"
L["DEATHKNIGHT:short"] = "DK"
L["WARLOCK:short"] = "Lock"
L["PRIEST:short"] = "Priest"
L["HUNTER:short"] = "Hunter"
L["ROGUE:short"] = "Rogue"
L["SHAMAN:short"] = "Shaman"
L["DRUID:short"] = "Druid"
L["PALADIN:short"] = "Pala"
L["MAGE:short"] = "Mage"
L["MONK:short"] = "Monk"

L["specID:250:short"] = "Blood"
L["specID:251:short"] = "Frost"
L["specID:252:short"] = "Unholy"
L["specID:102:short"] = "Balance"
L["specID:103:short"] = "Feral"
L["specID:104:short"] = "Guardian"
L["specID:105:short"] = "Resto"
L["specID:253:short"] = "BM"
L["specID:254:short"] = "Marks"
L["specID:255:short"] = "Surv"
L["specID:62:short"] = "Arcane"
L["specID:63:short"] = "Fire"
L["specID:64:short"] = "Frost"
L["specID:268:short"] = "Brew"
L["specID:269:short"] = "Wind"
L["specID:270:short"] = "Mist"
L["specID:65:short"] = "Holy"
L["specID:66:short"] = "Prot"
L["specID:70:short"] = "Retri"
L["specID:256:short"] = "Disc"
L["specID:257:short"] = "Holy"
L["specID:258:short"] = "Shadow"
L["specID:259:short"] = "Assa"
L["specID:260:short"] = "Combat"
L["specID:261:short"] = "Subtl"
L["specID:262:short"] = "Ele"
L["specID:263:short"] = "Enha"
L["specID:264:short"] = "Resto"
L["specID:265:short"] = "Affli"
L["specID:266:short"] = "Demo"
L["specID:267:short"] = "Destru"
L["specID:71:short"] = "Arms"
L["specID:72:short"] = "Fury"
L["specID:73:short"] = "Prot"

L["maxhealthTag"] = "Max Health"
L["maxpower:shortTag"] = "Max Power (Short)"
L["powerTag"] = "Power"
L["health:shortTag"] = "Health (Short)"
L["classTag"] = "Class"
L["class:shortTag"] = "Class (Short)"
L["power:percentageTag"] = "Power (Percentage)"
L["power:shortTag"] = "Power (Short)"
L["raceTag"] = "Race"
L["nameTag"] = "Name"
L["name:statusTag"] = "Name/Status"
L["specTag"] = "Spec"
L["spec:shortTag"] = "Spec (Short)"
L["health:percentageTag"] = "Health (Percentage)"
L["healthTag"] = "Health"
L["maxhealth:shortTag"] = "Max Health (Short)"
L["maxpowerTag"] = "Max Power"

-- Module names
L["CastBar"] = "Cast Bar"
L["ClassIcon"] = "Class Icon"
L["DRTracker"] = "DR Tracker"
L["HealthBar"] = "Health Bar"
L["PowerBar"] = "Power Bar"
L["TargetBar"] = "Target Bar"

-- General
L["Remaining time"] = true
L["Show cast time"] = true
L["Show delay"] = true
L["Show total time"] = true
L["Toggle cast time"] = true
L["Toggle delay"] = true
L["Toggle remaining time instead of cast time"] = true
L["Toggle total time"] = true
L["Use the global font size"] = true

L[" |T%s:20|t %s [%ss] %s"] = true
L["%s settings"] = true
L["** If this is not your first run please lock or move the frame to prevent this from happening **"] = true
L["Absorbs bar color"] = true
L["Absorbs color"] = true
L["Absorbs settings"] = true
L["Absorbs"] = true
L["Action"] = true
L["Active"] = true
L["Add click action"] = true
L["Add cooldowns group"] = true
L["Add new aura filter"] = true
L["Add new aura"] = true
L["Add tag"] = true
L["Add text"] = true
L["Add"] = true
L["Adjust bar width to the frame width"] = true
L["Adjust size to the frame size"] = true
L["Adjust size"] = true
L["Adjust width"] = true
L["Advanced options"] = true
L["Align of the text"] = true
L["Alpha of the icon border while the spell is being used"] = true
L["Alpha of the icon border while the spell is not on cooldown"] = true
L["Alpha of the icon border while the spell is on cooldown"] = true
L["Alpha of the icon while the spell is being used"] = true
L["Alpha of the icon while the spell is not on cooldown"] = true
L["Alpha of the icon while the spell is on cooldown"] = true
L["alt-"] = true
L["Anchor of the frame"] = true
L["Anchor of the health bar"] = true
L["Anchor"] = true
L["Announcement toggles"] = true
L["Announcements"] = true
L["Announces when an enemy drops below a certain health threshold"] = true
L["Announces when an enemy tries to resurrect a teammate"] = true
L["Announces when enemies sit down to drink"] = true
L["Announces when the spec of an enemy was detected"] = true
L["Arena"] = true
L["Attach drTracker to the given frame"] = true
L["Attach health bar to the given frame"] = true
L["Attach text to module bar"] = true
L["Attach to the given frame"] = true
L["Attach to"] = true
L["Auras"] = true
L["Available"] = true
L["Background color"] = true
L["Background padding"] = true
L["Bar height"] = true
L["Bar settings"] = true
L["Bar width"] = true
L["Bar"] = true
L["Blacklist"] = true
L["Blizzard's Floating Combat Text"] = true
L["Border color for spells in this category"] = true
L["Border transparency settings"] = true
L["Border transparency"] = true
L["Bottom left"] = true
L["Bottom right"] = true
L["Buffs"] = true
L["Button 4"] = true
L["Button 5"] = true
L["Cast spell"] = true
L["Cast text"] = true
L["Cast time text"] = true
L["CastBar Icon"] = true
L["Categories"] = true
L["Category settings"] = true
L["Category"] = true
L["Center left"] = true
L["Center right"] = true
L["Center"] = true
L["Choose how low an enemy must be before low health is announced"] = true
L["Choose how your announcements are displayed"] = true
L["Class color"] = true
L["Class icon"] = true
L["Class"] = true
L["ClassIcon"] = true
L["Click actions"] = true
L["Clicks"] = true
L["Code of your layout"] = true
L["Color of the cast bar background"] = true
L["Color of the cast bar when the spell can't be interrupted"] = true
L["Color of the cast bar"] = true
L["Color of the frame background"] = true
L["Color of the gloss"] = true
L["Color of the health bar background"] = true
L["Color of the health bar"] = true
L["Color of the highlight"] = true
L["Color of the power bar background"] = true
L["Color of the power bar"] = true
L["Color of the text"] = true
L["Color"] = true
L["Column grow"] = true
L["Cooldown reverse"] = true
L["Cooldown spiral"] = true
L["Cooldown starts on dispel"] = true
L["Cooldown starts when aura fades"] = true
L["Cooldowns group %i"] = true
L["Cooldowns"] = true
L["Copy all settings from arena to party"] = true
L["Copy all settings from party to arena"] = true
L["Copy from arena"] = true
L["Copy from party"] = true
L["Copy settings"] = true
L["Crop borders"] = true
L["ctrl-"] = true
L["Dead alpha"] = true
L["DEAD"] = true
L["Debuffs with buffs"] = true
L["Debuffs"] = true
L["Decrease the priority of spells in this category"] = true
L["Default color"] = true
L["Delete click action"] = true
L["Delete tag"] = true
L["Delete text"] = true
L["Delete"] = true
L["Destination"] = true
L["Disable all the spells in this category"] = true
L["Disable all the spells"] = true
L["Disable all"] = true
L["Disable this to be able to move the frames separately"] = true
L["Disabled"] = true
L["Display the cooldown spiral for the drTracker icons"] = true
L["Display the cooldown spiral for the important auras"] = true
L["Down left"] = true
L["Down right"] = true
L["Down"] = true
L["Drinking"] = true
L["DRINKING: %s (%s)"] = true
L["DRTracker"] = true
L["Duration: %is"] = true
L["Enable all the spells in this category"] = true
L["Enable all the spells"] = true
L["Enable all"] = true
L["Enable module"] = true
L["Error while importing layout: %s"] = true
L["Events which update the tag"] = true
L["Events"] = true
L["Example Spell Name"] = true
L["Export layout"] = true
L["Export your layout code"] = true
L["Filter function"] = true
L["Filter type"] = true
L["Filter"] = true
L["Filters"] = true
L["First run has been detected, displaying test frame"] = true
L["Font settings"] = true
L["Font"] = true
L["Frame level of the frame"] = true
L["Frame level"] = true
L["Frame scale"] = true
L["Frame settings"] = true
L["Frame"] = true
L["Function"] = true
L["General settings"] = true
L["General"] = true
L["GladiusEx Enemy Anchor - click to move"] = true
L["GladiusEx Party Anchor - click to move"] = true
L["Global font size"] = true
L["Global font"] = true
L["Global font, used by the modules"] = true
L["Gloss color"] = true
L["Gloss"] = true
L["Group frames"] = true
L["Group"] = true
L["Grow direction of the cooldowns"] = true
L["Grow direction of the icons"] = true
L["Grow direction"] = true
L["HealthBar"] = true
L["Height of the cast bar"] = true
L["Height of the health bar"] = true
L["Height of the power bar"] = true
L["Height"] = true
L["Hide talents until detected"] = true
L["Highlight border width"] = true
L["Highlight color"] = true
L["Highlight focus target"] = true
L["Highlight frame on mouseover"] = true
L["Highlight on mouseover"] = true
L["Highlight raid assist target"] = true
L["Highlight the player target"] = true
L["Highlight"] = true
L["Horizontal padding of the icons"] = true
L["Horizontal padding"] = true
L["Horizontal spacing of the icons"] = true
L["Horizontal spacing"] = true
L["Hover settings"] = true
L["Hover"] = true
L["How much the absorbs bar can grow outside the health bar, as a proportion of the unit's total health"] = true
L["How much the incoming heals bar can grow outside the health bar, as a proportion of the unit's total health"] = true
L["Icon border size"] = true
L["Icon position"] = true
L["Icon size"] = true
L["Icon transparency settings"] = true
L["Icon transparency"] = true
L["Icon"] = true
L["Icons max"] = true
L["Icons per column"] = true
L["Import layout"] = true
L["Import your layout code"] = true
L["Important auras"] = true
L["Incoming heals bar color"] = true
L["Incoming heals color"] = true
L["Incoming heals settings"] = true
L["Incoming heals"] = true
L["Increase the priority of spells in this category"] = true
L["Inverse"] = true
L["Invert the bar colors"] = true
L["Invert the dark/bright part of the cooldown spiral"] = true
L["Items"] = true
L["Layout code"] = true
L["Left and right"] = true
L["Left"] = true
L["Lock frames"] = true
L["Low health threshold"] = true
L["Low health"] = true
L["LOW HEALTH: %s (%s)"] = true
L["Margin between each button"] = true
L["Margin"] = true
L["Middle"] = true
L["MikScrollingBattleText"] = true
L["Modifier"] = true
L["Mouse button"] = true
L["Name of the aura"] = true
L["Name of the tag"] = true
L["Name of the text element"] = true
L["Name"] = true
L["New aura"] = true
L["None"] = true
L["Not interruptible color"] = true
L["Number of aura icons per column"] = true
L["Number of icons per column"] = true
L["Number of max buffs"] = true
L["Number of max icons"] = true
L["Offset X"] = true
L["Offset Y"] = true
L["On cooldown"] = true
L["Options"] = true
L["Out of range alpha"] = true
L["Outside bar limit"] = true
L["Padding of the background"] = true
L["Parrot"] = true
L["Party"] = true
L["Pet"] = true
L["Player focus target settings"] = true
L["Player focus target"] = true
L["Player target settings"] = true
L["Player target"] = true
L["Position of the cast bar icon"] = true
L["Position of the drTracker"] = true
L["Position of the frame"] = true
L["Position of the target bar class icon"] = true
L["Position settings"] = true
L["Position"] = true
L["Power type"] = true
L["PowerBar"] = true
L["Priority of the highlight"] = true
L["Priority"] = true
L["Race"] = true
L["Raid assist settings"] = true
L["Raid assist target"] = true
L["Raid icon target %i"] = true
L["Raid icon targets"] = true
L["Raid Warning"] = true
L["Relative point of the frame"] = true
L["Relative point of the health bar"] = true
L["Relative point"] = true
L["Remove this cooldowns group"] = true
L["Replaces: %s"] = true
L["Required aura: %s"] = true
L["Reset all arena settings to their default values"] = true
L["Reset all party settings to their default values"] = true
L["Reset arena settings"] = true
L["Reset module"] = true
L["Reset party settings"] = true
L["Reset settings"] = true
L["Resets: %s"] = true
L["RESURRECTING: %s (%s)"] = true
L["Resurrection"] = true
L["Right"] = true
L["Role"] = true
L["Say"] = true
L["Scale of the frame"] = true
L["Scrolling Combat Text"] = true
L["Select a modifier for this click action"] = true
L["Select what priority the aura should have - higher equals more priority"] = true
L["Select what this click action does"] = true
L["Select which mouse button this click action uses"] = true
L["Self"] = true
L["Shared cooldown: %s (%is)"] = true
L["Shield icon"] = true
L["shift-"] = true
L["Show absorbs"] = true
L["Show border around focus target"] = true
L["Show border around raid assist"] = true
L["Show border around raid target %i"] = true
L["Show important auras instead of the class icon"] = true
L["Show incoming heals"] = true
L["Show only dispellable"] = true
L["Show only mine"] = true
L["Show party frames"] = true
L["Show"] = true
L["Size of the aura icons"] = true
L["Size of the cooldown icon borders"] = true
L["Size of the cooldown icons"] = true
L["Size of the drTracker"] = true
L["Size of the icon"] = true
L["Size of the icons"] = true
L["Size of the text"] = true
L["Size settings"] = true
L["Size"] = true
L["Space between the icons"] = true
L["Spacing"] = true
L["SPEC DETECTED: %s (%s/%s)"] = true
L["Spec detection"] = true
L["Spec"] = true
L["Spec"] = true
L["Spell name / Macro text"] = true
L["Spells in each group have their own row or column"] = true
L["Stealth alpha"] = true
L["Stop testing"] = true
L["Tag settings"] = true
L["Tag"] = true
L["Tag: %s"] = true
L["Tags"] = true
L["Talent"] = true
L["TargetBar"] = true
L["Test 2v2"] = true
L["Test 3v3"] = true
L["Test 5v5"] = true
L["Test frames"] = true
L["Test units"] = true
L["Testing settings"] = true
L["Testing"] = true
L["Text align of the cast text"] = true
L["Text align of the cast time text"] = true
L["Text align"] = true
L["Text color of the cast text"] = true
L["Text color of the cast time text"] = true
L["Text color of the DR text"] = true
L["Text color"] = true
L["Text settings"] = true
L["Text size of the cast text"] = true
L["Text size of the cast time text"] = true
L["Text size of the DR text"] = true
L["Text size of the global font"] = true
L["Text size"] = true
L["Text to be displayed"] = true
L["Text"] = true
L["Texts"] = true
L["Texture of the cast bar"] = true
L["Texture of the health bar"] = true
L["Texture of the power bar"] = true
L["Texture"] = true
L["The direction you want the frames to grow in"] = true
L["Toggle aura buffs"] = true
L["Toggle aura debuffs"] = true
L["Toggle cast text"] = true
L["Toggle cast time text"] = true
L["Toggle default color"] = true
L["Toggle display of absorbs in the health bar"] = true
L["Toggle display of advanced options"] = true
L["Toggle display of incoming heals in the health bar"] = true
L["Toggle gloss on the icon"] = true
L["Toggle health bar class color"] = true
L["Toggle if the frames can be moved"] = true
L["Toggle if the icon borders should be cropped or not"] = true
L["Toggle if you want to use the global font size"] = true
L["Toggle the cast bar shield icon for not interruptible spells"] = true
L["Toggle the cast bar spell icon"] = true
L["Toggle the target bar class icon"] = true
L["Toggle to show your party frames"] = true
L["Top left"] = true
L["Top right"] = true
L["Transparency for dead units"] = true
L["Transparency for units in stealth"] = true
L["Transparency for units out of range"] = true
L["Unit power type"] = true
L["Unit race"] = true
L["Unit settings"] = true
L["Unit talent specialization"] = true
L["Units"] = true
L["Up and down"] = true
L["Up left"] = true
L["Up right"] = true
L["Up"] = true
L["Use global font size"] = true
L["Valid slash commands are:"] = true
L["Vertical padding of the icons"] = true
L["Vertical padding"] = true
L["Vertical spacing of the icons"] = true
L["Vertical spacing"] = true
L["Welcome to GladiusEx!"] = true
L["When available, show specialization instead of class icons"] = true
L["Whitelist"] = true
L["Widget settings"] = true
L["Widget"] = true
L["Width of the bar"] = true
L["Width of the cast bar"] = true
L["Width of the health bar"] = true
L["Width of the module bars"] = true
L["Width"] = true
L["X offset of the cast text"] = true
L["X offset of the cast time text"] = true
L["X offset of the frame"] = true
L["X offset of the health bar"] = true
L["X offset"] = true
L["Y offset of the cast text"] = true
L["Y offset of the cast time text"] = true
L["Y offset of the frame"] = true
L["Y offset of the health bar"] = true
L["Y offset"] = true
