local L = LibStub("AceLocale-3.0"):NewLocale("GladiusEx", "enUS", true)

L["** If this is not your first run please lock or move the frame to prevent this from happening **"] = true
L["Action"] = true
L["Add click action"] = true
L["Add new Aura"] = true
L["Add Tag"] = true
L["Add tag"] = true
L["Add Text"] = true
L["Add text"] = true
L["Add"] = true
L["Adjust cast bar width to the frame width"] = true
L["Adjust class icon size to the frame size"] = true
L["Adjust drTracker size to the frame size"] = true
L["Adjust health bar width to the frame width"] = true
L["Adjust power bar width to the frame width"] = true
L["Advanced Options"] = true
L["alt-"] = true
L["Anchor of the auras"] = true
L["Anchor of the cast bar"] = true
L["Anchor of the class icon"] = true
L["Anchor of the cooldowns"] = true
L["Anchor of the drTracker"] = true
L["Anchor of the health bar"] = true
L["Anchor of the power bar"] = true
L["Announcement toggles"] = true
L["Announcements settings"] = true
L["Announcements"] = true
L["Announces when an enemy drops below a certain health threshold."] = true
L["Announces when an enemy tries to resurrect a teammate."] = true
L["Announces when enemies sit down to drink."] = true
L["Announces when the spec of an enemy was detected."] = true
L["Attach auras to the given frame"] = true
L["Attach cast bar to the given frame"] = true
L["Attach class icon to given frame"] = true
L["Attach cooldowns to the given frame"] = true
L["Attach drTracker to the given frame"] = true
L["Attach health bar to the given frame"] = true
L["Attach power bar to the given frame"] = true
L["Attach text to module bar"] = true
L["Aura Icon Size"] = true
L["Aura Icons Max"] = true
L["Aura Icons Per Column"] = true
L["Auras Anchor"] = true
L["Auras Attach To"] = true
L["Auras Buffs"] = true
L["Auras Column Grow"] = true
L["Auras Debuffs"] = true
L["Auras Offset X"] = true
L["Auras Offset Y"] = true
L["Auras Relative Point"] = true
L["Auras settings"] = true
L["Auras Spacing Horizontal"] = true
L["Auras Spacing Vertical"] = true
L["Auras"] = true
L["Background Color"] = true
L["Background Padding"] = true
L["Bar settings"] = true
L["Bar width"] = true
L["Bar"] = true
L["Blacklist"] = true
L["Blizzard's Floating Combat Text"] = true
L["Border color for spells in this category"] = true
L["Bottom Left"] = true
L["Bottom Right"] = true
L["Buffs"] = true
L["Button 4"] = true
L["Button 5"] = true
L["Cast Bar Adjust Width"] = true
L["Cast Bar Anchor"] = true
L["Cast Bar Attach To"] = true
L["Cast Bar Background Color"] = true
L["Cast Bar Color"] = true
L["Cast Bar Height"] = true
L["Cast Bar Icon Position"] = true
L["Cast Bar Icon"] = true
L["Cast Bar Inverse"] = true
L["Cast Bar Offset X"] = true
L["Cast Bar Offset Y"] = true
L["Cast Bar Relative Point"] = true
L["Cast Bar Texture"] = true
L["Cast Bar Width"] = true
L["Cast Spell"] = true
L["Cast Text Align"] = true
L["Cast Text Color"] = true
L["Cast Text Offset X"] = true
L["Cast Text Offset Y"] = true
L["Cast Text Size"] = true
L["Cast Text"] = true
L["Cast Time Offset X"] = true
L["Cast Time Offset Y"] = true
L["Cast Time Text Align"] = true
L["Cast Time Text Color"] = true
L["Cast Time Text Size"] = true
L["Cast Time Text"] = true
L["CastBar Icon"] = true
L["CastBar settings"] = true
L["CastBar"] = true
L["Categories"] = true
L["Category settings"] = true
L["Category"] = true
L["Center Left"] = true
L["Center Right"] = true
L["CENTER"] = true
L["Choose how low an enemy must be before low health is announced."] = true
L["Choose how your announcements are displayed."] = true
L["Class Icon Adjust Size"] = true
L["Class Icon Anchor"] = true
L["Class Icon Attach To"] = true
L["Class Icon Cooldown Reverse"] = true
L["Class Icon Cooldown Spiral"] = true
L["Class Icon Frame Level"] = true
L["Class Icon Gloss Color"] = true
L["Class Icon Gloss"] = true
L["Class Icon Offset X"] = true
L["Class Icon Offset Y"] = true
L["Class Icon Position"] = true
L["Class Icon Relative Point"] = true
L["Class Icon Size"] = true
L["Class"] = true
L["ClassIcon settings"] = true
L["ClassIcon"] = true
L["Click Actions"] = true
L["Clicks settings"] = true
L["Clicks"] = true
L["Code of your layout."] = true
L["Color of the cast bar background"] = true
L["Color of the cast bar"] = true
L["Color of the class icon gloss"] = true
L["Color of the drTracker icon gloss"] = true
L["Color of the focus target border"] = true
L["Color of the frame background"] = true
L["Color of the health bar background"] = true
L["Color of the health bar"] = true
L["Color of the highlight frame"] = true
L["Color of the power bar background"] = true
L["Color of the power bar"] = true
L["Color of the raid assist border"] = true
L["Color of the target border"] = true
L["Color"] = true
L["Cooldown Icon Size"] = true
L["Cooldown Icons Max"] = true
L["Cooldown Icons Per Column"] = true
L["Cooldowns Anchor"] = true
L["Cooldowns Attach To"] = true
L["Cooldowns Column Grow"] = true
L["Cooldowns Offset X"] = true
L["Cooldowns Offset Y"] = true
L["Cooldowns Relative Point"] = true
L["Cooldowns settings"] = true
L["Cooldowns Spacing Horizontal"] = true
L["Cooldowns Spacing Vertical"] = true
L["Cooldowns"] = true
L["Crop Borders"] = true
L["ctrl-"] = true
L["DEAD"] = true
L["Debuffs"] = true
L["Decrease the priority of spells in this category"] = true
L["Delete Click Action"] = true
L["Delete Tag"] = true
L["Delete Text"] = true
L["Delete"] = true
L["Destination"] = true
L["Disable all the spells in this category"] = true
L["Disable all the spells"] = true
L["Disable all"] = true
L["Display the cooldown spiral for important auras"] = true
L["Down Left"] = true
L["Down Right"] = true
L["Down"] = true
L["DR Text Color"] = true
L["DR Text Size"] = true
L["Drinking"] = true
L["DRINKING: %s (%s)"] = true
L["DRTracker Adjust Size"] = true
L["DRTracker Anchor"] = true
L["DRTracker Attach To"] = true
L["DRTracker Cooldown Reverse"] = true
L["DRTracker Cooldown Spiral"] = true
L["DRTracker Frame Level"] = true
L["DRTracker Gloss Color"] = true
L["DRTracker Gloss"] = true
L["DRTracker Offset X"] = true
L["DRTracker Offset Y"] = true
L["DRTracker Position"] = true
L["DRTracker Relative Point"] = true
L["DRTracker settings"] = true
L["DRTracker Size"] = true
L["DRTracker Space"] = true
L["DRTracker"] = true
L["Enable all the spells in this category"] = true
L["Enable all the spells"] = true
L["Enable all"] = true
L["Enable Module"] = true
L["Error while importing layout: %s"] = true
L["Events which update the tag"] = true
L["Events"] = true
L["Example Spell Name"] = true
L["Export layout"] = true
L["Export your layout code."] = true
L["Filter Function"] = true
L["Filter"] = true
L["First run has been detected, displaying test frame."] = true
L["Font settings"] = true
L["Font"] = true
L["Frame level of the class icon"] = true
L["Frame level of the drTracker"] = true
L["Frame scale"] = true
L["Frame settings"] = true
L["Frame"] = true
L["Function"] = true
L["General settings"] = true
L["General"] = true
L["GladiusEx Enemy Anchor - click to move"] = true
L["GladiusEx Party Anchor - click to move"] = true
L["Global Font Size"] = true
L["Global Font"] = true
L["Global font, used by the modules"] = true
L["Group Buttons"] = true
L["Group"] = true
L["Grow direction of the auras"] = true
L["Grow direction of the cooldowns"] = true
L["Grow Direction"] = true
L["Health bar adjust width"] = true
L["Health Bar Anchor"] = true
L["Health Bar Attach To"] = true
L["Health bar background color"] = true
L["Health bar class color"] = true
L["Health bar color"] = true
L["Health bar height"] = true
L["Health bar inverse"] = true
L["Health bar offset X"] = true
L["Health bar offset Y"] = true
L["Health Bar Relative Point"] = true
L["Health bar texture"] = true
L["Health bar width"] = true
L["HealthBar settings"] = true
L["HealthBar"] = true
L["Height of the cast bar"] = true
L["Height of the health bar"] = true
L["Height of the power bar"] = true
L["Hide talents until detected"] = true
L["Highlight border width"] = true
L["Highlight Color"] = true
L["Highlight Focus Target Color"] = true
L["Highlight Focus Target Priority"] = true
L["Highlight Focus Target"] = true
L["Highlight frame on mouseover"] = true
L["Highlight On Mouseover"] = true
L["Highlight Priority"] = true
L["Highlight Raid Assist Color"] = true
L["Highlight Raid Assist Priority"] = true
L["Highlight Raid Assist"] = true
L["Highlight settings"] = true
L["Highlight Target Color"] = true
L["Highlight Target Priority"] = true
L["Highlight Target"] = true
L["Highlight"] = true
L["Horizontal spacing of the auras"] = true
L["Horizontal spacing of the cooldowns"] = true
L["Hover settings"] = true
L["Hover"] = true
L["If this is toggle buttons can be moved separately"] = true
L["Import layout"] = true
L["Import your layout code."] = true
L["Important Auras"] = true
L["Increase the priority of spells in this category"] = true
L["Inverse the cast bar"] = true
L["Inverse the health bar"] = true
L["Inverse the power bar"] = true
L["Invert the dark/bright part of the cooldown spiral"] = true
L["Items"] = true
L["Layout Code"] = true
L["Layout settings"] = true
L["Layout"] = true
L["Left and right"] = true
L["LEFT"] = true
L["Left"] = true
L["Lock frame"] = true
L["Low health threshold"] = true
L["Low health"] = true
L["LOW HEALTH: %s (%s)"] = true
L["Margin between each button"] = true
L["Margin"] = true
L["Middle"] = true
L["MikScrollingBattleText"] = true
L["Modifier"] = true
L["Mouse button"] = true
L["Name of the aura"] = true
L["Name of the tag"] = true
L["Name of the text element"] = true
L["Name"] = true
L["New Aura"] = true
L["None"] = true
L["Number of aura icons per column"] = true
L["Number of cooldown icons per column"] = true
L["Number of max buffs"] = true
L["Number of max cooldowns"] = true
L["Number of max Debuffs"] = true
L["Options"] = true
L["Padding of the background"] = true
L["Parrot"] = true
L["Party"] = true
L["Player focus target settings"] = true
L["Player Focus Target"] = true
L["Player target settings"] = true
L["Player Target"] = true
L["Position of the cast bar icon"] = true
L["Position of the class icon"] = true
L["Position of the target bar class icon"] = true
L["Position settings"] = true
L["Position"] = true
L["Power Bar Adjust Width"] = true
L["Power Bar Anchor"] = true
L["Power Bar Attach To"] = true
L["Power Bar Background Color"] = true
L["Power Bar Color"] = true
L["Power Bar Default Color"] = true
L["Power Bar Height"] = true
L["Power Bar Inverse"] = true
L["Power Bar Offset X"] = true
L["Power Bar Offset Y"] = true
L["Power Bar Relative Point"] = true
L["Power Bar Texture"] = true
L["Power Bar Width"] = true
L["PowerBar settings"] = true
L["PowerBar"] = true
L["Priority of the focus target border"] = true
L["Priority of the raid assist border"] = true
L["Priority of the target border"] = true
L["Priority"] = true
L["Raid assist settings"] = true
L["Raid Assist Target"] = true
L["Raid Icon Target %i"] = true
L["Raid Icon Targets"] = true
L["Raid Warning"] = true
L["Relative point of the auras"] = true
L["Relative point of the cast bar"] = true
L["Relative point of the class icon"] = true
L["Relative point of the cooldowns"] = true
L["Relative point of the drTracker"] = true
L["Relative point of the health bar"] = true
L["Relative point of the power bar"] = true
L["Reset Module"] = true
L["RESURRECTING: %s (%s)"] = true
L["Resurrection"] = true
L["RIGHT"] = true
L["Right"] = true
L["Role"] = true
L["Say"] = true
L["Scale of the frame"] = true
L["Scrolling Combat Text"] = true
L["Select a modifier for this click action"] = true
L["Select what priority the aura should have - higher equals more priority"] = true
L["Select what this Click Action does"] = true
L["Select which mouse button this click action uses"] = true
L["Self"] = true
L["shift-"] = true
L["Show border around player target"] = true
L["Show border around raid assist"] = true
L["Show border around raid target %i"] = true
L["Show Debuffs with Buffs"] = true
L["Show important auras instead of the class icon"] = true
L["Show only dispellable"] = true
L["Show only mine"] = true
L["Show party frames"] = true
L["Show"] = true
L["Size of the aura icons"] = true
L["Size of the class icon"] = true
L["Size of the cooldown icons"] = true
L["Size of the drTracker"] = true
L["Size settings"] = true
L["Size"] = true
L["Space between the icons"] = true
L["SPEC DETECTED: %s (%s/%s)"] = true
L["Spec Detection"] = true
L["Spec"] = true
L["Spell Name / Macro Text"] = true
L["Spells in each group have their own row or column"] = true
L["Tag settings"] = true
L["Tag"] = true
L["Tag: %s"] = true
L["Tags settings"] = true
L["Tags"] = true
L["Target Bar Anchor"] = true
L["Target Bar Attach To"] = true
L["Target bar background color"] = true
L["Target bar class color"] = true
L["Target bar class icon"] = true
L["Target bar color"] = true
L["Target bar height"] = true
L["Target Bar Icon Crop Borders"] = true
L["Target bar icon position"] = true
L["Target bar inverse"] = true
L["Target bar offset X"] = true
L["Target bar offset Y"] = true
L["Target Bar Relative Point"] = true
L["Target bar texture"] = true
L["Target bar width"] = true
L["TargetBar settings"] = true
L["TargetBar"] = true
L["Text align of the cast text"] = true
L["Text align of the cast time text"] = true
L["Text align of the text"] = true
L["Text Align"] = true
L["Text Attach To"] = true
L["Text color of the cast text"] = true
L["Text color of the cast time text"] = true
L["Text color of the DR text"] = true
L["Text color of the text"] = true
L["Text Color"] = true
L["Text Offset X"] = true
L["Text Offset Y"] = true
L["Text settings"] = true
L["Text size of the cast text"] = true
L["Text size of the cast time text"] = true
L["Text size of the DR text"] = true
L["Text size of the power info text"] = true
L["Text size of the text"] = true
L["Text Size"] = true
L["Text to be displayed"] = true
L["Text"] = true
L["Texts"] = true
L["Texture of the cast bar"] = true
L["Texture of the health bar"] = true
L["Texture of the power bar"] = true
L["The Direction you want the frame to go in."] = true
L["Toggle advanced options"] = true
L["Toggle aura buffs"] = true
L["Toggle aura debuffs"] = true
L["Toggle cast text"] = true
L["Toggle cast time text"] = true
L["Toggle gloss on the class icon"] = true
L["Toggle gloss on the drTracker icon"] = true
L["Toggle health bar class color"] = true
L["Toggle if the class icon borders should be cropped or not."] = true
L["Toggle if the frame can be moved"] = true
L["Toggle if the target bar icon borders should be cropped or not."] = true
L["Toggle if you want to use the global font size"] = true
L["Toggle power bar default color"] = true
L["Toggle the cast icon"] = true
L["Toggle the target bar class icon"] = true
L["Top Left"] = true
L["Top Right"] = true
L["Up Left"] = true
L["Up Right"] = true
L["Up"] = true
L["Use Global Font Size"] = true
L["Valid slash commands are:"] = true
L["Vertical spacing of the auras"] = true
L["Vertical spacing of the cooldowns"] = true
L["Welcome to GladiusEx!"] = true
L["When available, show specialization instead of class icons"] = true
L["Whitelist"] = true
L["Widget settings"] = true
L["Widget"] = true
L["Width of the cast bar"] = true
L["Width of the health bar"] = true
L["Width of the module bars"] = true
L["Width of the power bar"] = true
L["X offset of the auras"] = true
L["X offset of the cast bar"] = true
L["X offset of the cast text"] = true
L["X Offset of the cast time text"] = true
L["X offset of the class icon"] = true
L["X offset of the cooldowns"] = true
L["X offset of the drTracker"] = true
L["X offset of the health bar"] = true
L["X offset of the power bar"] = true
L["X offset of the text"] = true
L["Y offset of the auras"] = true
L["Y offset of the cast text"] = true
L["Y Offset of the cast time text"] = true
L["Y offset of the castbar"] = true
L["Y offset of the class icon"] = true
L["Y offset of the cooldowns"] = true
L["Y offset of the drTracker"] = true
L["Y offset of the health bar"] = true
L["Y offset of the text"] = true

		-- cooldowns module
L["cat:pvp_trinket"] = "PvP Trinket"
L["cat:mass_dispel"] = "Mass Dispel"
L["cat:cc"] = "CC"
L["cat:offensive"] = "Offensive"
L["cat:defensive"] = "Defensive"
L["cat:silence"] = "Silence"
L["cat:interrupt"] = "Interrupt"
L["cat:dispel"] = "Dispel"
L["cat:heal"] = "Heal"
L["cat:knockback"] = "Knockback"
L["cat:stun"] = "Stun"
L["cat:immune"] = "Immune"
L["cat:uncat"] = "Uncategorized"

L["maxhealthTag"] = "Max Health"
L["maxpower:shortTag"] = "Max Power (Short)"
L["powerTag"] = "Power"
L["health:shortTag"] = "Health (Short)"
L["classTag"] = "Class"
L["class:shortTag"] = "Class (Short)"
L["power:percentageTag"] = "Power (Percentage)"
L["power:shortTag"] = "Power (Short)"
L["raceTag"] = "Race"
L["nameTag"] = "Name"
L["name:statusTag"] = "Name/Status"
L["specTag"] = "Spec"
L["spec:shortTag"] = "Spec (Short)"
L["health:percentageTag"] = "Health (Percentage)"
L["healthTag"] = "Health"
L["maxhealth:shortTag"] = "Max Health (Short)"
L["maxpowerTag"] = "Max Power"

		-- Specs
L["specID:250:short"] = "Blood"
L["specID:251:short"] = "Frost"
L["specID:252:short"] = "Unholy"

L["specID:102:short"] = "Balance"
L["specID:103:short"] = "Feral"
L["specID:104:short"] = "Guardian"
L["specID:105:short"] = "Resto"

L["specID:253:short"] = "BM"
L["specID:254:short"] = "Marks"
L["specID:255:short"] = "Surv"

L["specID:62:short"] = "Arcane"
L["specID:63:short"] = "Fire"
L["specID:64:short"] = "Frost"

L["specID:268:short"] = "Brew"
L["specID:269:short"] = "Wind"
L["specID:270:short"] = "Mist"

L["specID:65:short"] = "Holy"
L["specID:66:short"] = "Prot"
L["specID:70:short"] = "Retri"

L["specID:256:short"] = "Disc"
L["specID:257:short"] = "Holy"
L["specID:258:short"] = "Shadow"

L["specID:259:short"] = "Assa"
L["specID:260:short"] = "Combat"
L["specID:261:short"] = "Subtl"

L["specID:262:short"] = "Ele"
L["specID:263:short"] = "Enha"
L["specID:264:short"] = "Resto"

L["specID:265:short"] = "Affli"
L["specID:266:short"] = "Demo"
L["specID:267:short"] = "Destru"

L["specID:71:short"] = "Arms"
L["specID:72:short"] = "Fury"
L["specID:73:short"] = "Prot"

		-- Classes
L["WARRIOR:short"] = "Warr"
L["DEATHKNIGHT:short"] = "DK"
L["WARLOCK:short"] = "Lock"
L["PRIEST:short"] = "Priest"
L["HUNTER:short"] = "Hunter"
L["ROGUE:short"] = "Rogue"
L["SHAMAN:short"] = "Shaman"
L["DRUID:short"] = "Druid"
L["PALADIN:short"] = "Pala"
L["MAGE:short"] = "Mage"
L["MONK:short"] = "Monk"
